### PR TITLE
Add suffix to PG User for Kerberos/GSS Authentication

### PR DESCRIPTION
**Pull request by bradyclifford**
Ability to add a FQDN suffix to the user role creation when using Kerberos/GSS

i.e. Postgres Integrated Security with Kerberos/GSS with Ldap requires the domain name added to the end of the login:
```
Ldap username: test
Ldap Domain: DOMAIN.COM
Needs to be created in Postgres as: test@DOMAIN.COM
```

### CODE REVIEW

**Comment by larskanis** [comment]
I usually solve this kind of issues per `pg_ident.conf` . Did you try this: https://www.postgresql.org/docs/current/static/auth-username-maps.html ?

**Comment by bradyclifford** [comment]
I have not yet.  Let me get with my dba and try this out.  I will break out the other changes included in this PR into their own for further discussion in the meantime.

**Comment by bradyclifford** [comment]
Our security team will not allow for stripping the domain naming using the username maps as you suggested @larskanis.  The Postgres usernames will need to include the domain name.

The reasoning given by our security team, from the [Postgres Documentation](https://www.postgresql.org/docs/9.6/static/auth-methods.html#GSSAPI-AUTH):
> PostgreSQL also supports a parameter to strip the realm from the principal. This method is supported for backwards compatibility and is strongly discouraged as it is then impossible to distinguish different users with the same user name but coming from different realms.

Are you aware of another solution other then what I have provided in this PR?

**Comment by bradyclifford** [comment]
Possibly using `userPrincipalName` instead of `sAMAccountName`?

**Comment by bradyclifford** [comment]
The problem with using `userPrincipalName` is the domain name is lower case.  We have to work with best practices where the Kerberos authentication expects an uppercase domain name.

Because we work with multiple realms as well, we cannot utilize the username maps; removing the domain name for a pg user.

With that, I am still requesting that we allow a suffix to be added to the pg user being created.

**Comment by bradyclifford** [comment]
We ended up convincing out security team to use a lowercase domain name.  A workaround has been found and this PR can be closed.

**Pull request closed without merging**
